//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://tempuri.org/", ClrNamespace = "tempuri.org")]

namespace tempuri.org
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ArrayOfString", Namespace = "http://tempuri.org/", ItemName = "string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OfficeIMMessageBody", Namespace = "http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(tempuri.org.OfficeIMMessageMuiltAttbBody))]
    public partial class OfficeIMMessageBody : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string TitleField;

        private string ContentField;

        private string FromUserIdField;

        private string FromUserNameField;

        private tempuri.org.ArrayOfString ToUserIdField;

        private tempuri.org.ArrayOfString ToUserNameField;

        private string AttachmentFileNameField;

        private byte[] AttachmentFileContentField;

        private int AttachmentFileLengthField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string FromUserId
        {
            get
            {
                return this.FromUserIdField;
            }
            set
            {
                this.FromUserIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string FromUserName
        {
            get
            {
                return this.FromUserNameField;
            }
            set
            {
                this.FromUserNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public tempuri.org.ArrayOfString ToUserId
        {
            get
            {
                return this.ToUserIdField;
            }
            set
            {
                this.ToUserIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public tempuri.org.ArrayOfString ToUserName
        {
            get
            {
                return this.ToUserNameField;
            }
            set
            {
                this.ToUserNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string AttachmentFileName
        {
            get
            {
                return this.AttachmentFileNameField;
            }
            set
            {
                this.AttachmentFileNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public byte[] AttachmentFileContent
        {
            get
            {
                return this.AttachmentFileContentField;
            }
            set
            {
                this.AttachmentFileContentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 8)]
        public int AttachmentFileLength
        {
            get
            {
                return this.AttachmentFileLengthField;
            }
            set
            {
                this.AttachmentFileLengthField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OfficeIMMessageMuiltAttbBody", Namespace = "http://tempuri.org/")]
    public partial class OfficeIMMessageMuiltAttbBody : tempuri.org.OfficeIMMessageBody
    {

        private tempuri.org.MuiltAttb[] MuiltAttbsField;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public tempuri.org.MuiltAttb[] MuiltAttbs
        {
            get
            {
                return this.MuiltAttbsField;
            }
            set
            {
                this.MuiltAttbsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MuiltAttb", Namespace = "http://tempuri.org/")]
    public partial class MuiltAttb : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AttachmentFileNameField;

        private byte[] AttachmentFileContentField;

        private int AttachmentFileLengthField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string AttachmentFileName
        {
            get
            {
                return this.AttachmentFileNameField;
            }
            set
            {
                this.AttachmentFileNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public byte[] AttachmentFileContent
        {
            get
            {
                return this.AttachmentFileContentField;
            }
            set
            {
                this.AttachmentFileContentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public int AttachmentFileLength
        {
            get
            {
                return this.AttachmentFileLengthField;
            }
            set
            {
                this.AttachmentFileLengthField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetMailPara", Namespace = "http://tempuri.org/")]
    public partial class GetMailPara : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string nameField;

        private string strField;

        private int pageField;

        private int congtField;

        private string tokenField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string str
        {
            get
            {
                return this.strField;
            }
            set
            {
                this.strField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public int page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public int congt
        {
            get
            {
                return this.congtField;
            }
            set
            {
                this.congtField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NewShowapi_res_body_listOfNewReceiveMailBodyEntity", Namespace = "http://tempuri.org/")]
    public partial class NewShowapi_res_body_listOfNewReceiveMailBodyEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int allPagesField;

        private int currentPageField;

        private int allNumField;

        private int unreadField;

        private int maxResultField;

        private tempuri.org.NewReceiveMailBodyEntity[] contentlistField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int allPages
        {
            get
            {
                return this.allPagesField;
            }
            set
            {
                this.allPagesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int currentPage
        {
            get
            {
                return this.currentPageField;
            }
            set
            {
                this.currentPageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public int allNum
        {
            get
            {
                return this.allNumField;
            }
            set
            {
                this.allNumField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public int unread
        {
            get
            {
                return this.unreadField;
            }
            set
            {
                this.unreadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public int maxResult
        {
            get
            {
                return this.maxResultField;
            }
            set
            {
                this.maxResultField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public tempuri.org.NewReceiveMailBodyEntity[] contentlist
        {
            get
            {
                return this.contentlistField;
            }
            set
            {
                this.contentlistField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "NewReceiveMailBodyEntity", Namespace = "http://tempuri.org/")]
    public partial class NewReceiveMailBodyEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int idField;

        private string TostrField;

        private System.DateTime DateField;

        private string CcField;

        private string BccField;

        private string FromstrField;

        private string FromAddressField;

        private string SenderAddressField;

        private string SubjectField;

        private string BodyField;

        private string HtmlField;

        private string FolderTypeField;

        private tempuri.org.AttachmentBean[] AttachmentsField;

        private int AttaCountField;

        private bool StarField;

        private int StatusField;

        private int unreadField;

        private byte[] richField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string Tostr
        {
            get
            {
                return this.TostrField;
            }
            set
            {
                this.TostrField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string Cc
        {
            get
            {
                return this.CcField;
            }
            set
            {
                this.CcField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string Bcc
        {
            get
            {
                return this.BccField;
            }
            set
            {
                this.BccField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string Fromstr
        {
            get
            {
                return this.FromstrField;
            }
            set
            {
                this.FromstrField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 6)]
        public string FromAddress
        {
            get
            {
                return this.FromAddressField;
            }
            set
            {
                this.FromAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string SenderAddress
        {
            get
            {
                return this.SenderAddressField;
            }
            set
            {
                this.SenderAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string Html
        {
            get
            {
                return this.HtmlField;
            }
            set
            {
                this.HtmlField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 11)]
        public string FolderType
        {
            get
            {
                return this.FolderTypeField;
            }
            set
            {
                this.FolderTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 12)]
        public tempuri.org.AttachmentBean[] Attachments
        {
            get
            {
                return this.AttachmentsField;
            }
            set
            {
                this.AttachmentsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 13)]
        public int AttaCount
        {
            get
            {
                return this.AttaCountField;
            }
            set
            {
                this.AttaCountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 14)]
        public bool Star
        {
            get
            {
                return this.StarField;
            }
            set
            {
                this.StarField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 15)]
        public int Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 16)]
        public int unread
        {
            get
            {
                return this.unreadField;
            }
            set
            {
                this.unreadField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 17)]
        public byte[] rich
        {
            get
            {
                return this.richField;
            }
            set
            {
                this.richField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AttachmentBean", Namespace = "http://tempuri.org/")]
    public partial class AttachmentBean : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string NameField;

        private int indexField;

        private string SizeField;

        private byte[] AttaStreamField;

        private string pathField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string Size
        {
            get
            {
                return this.SizeField;
            }
            set
            {
                this.SizeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public byte[] AttaStream
        {
            get
            {
                return this.AttaStreamField;
            }
            set
            {
                this.AttaStreamField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetMailInfoPara", Namespace = "http://tempuri.org/")]
    public partial class GetMailInfoPara : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string idField;

        private string tokenField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "SendEmailSoap")]
public interface SendEmailSoap
{

    // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 title 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SendEx", ReplyAction = "*")]
    SendExResponse SendEx(SendExRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SendEx", ReplyAction = "*")]
    System.Threading.Tasks.Task<SendExResponse> SendExAsync(SendExRequest request);

    // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 title 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/Send", ReplyAction = "*")]
    SendResponse Send(SendRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/Send", ReplyAction = "*")]
    System.Threading.Tasks.Task<SendResponse> SendAsync(SendRequest request);

    // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 messageBody 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SendToOfficeIM", ReplyAction = "*")]
    SendToOfficeIMResponse SendToOfficeIM(SendToOfficeIMRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SendToOfficeIM", ReplyAction = "*")]
    System.Threading.Tasks.Task<SendToOfficeIMResponse> SendToOfficeIMAsync(SendToOfficeIMRequest request);

    // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 messageBody 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SendToOfficeIMMulAtt", ReplyAction = "*")]
    SendToOfficeIMMulAttResponse SendToOfficeIMMulAtt(SendToOfficeIMMulAttRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/SendToOfficeIMMulAtt", ReplyAction = "*")]
    System.Threading.Tasks.Task<SendToOfficeIMMulAttResponse> SendToOfficeIMMulAttAsync(SendToOfficeIMMulAttRequest request);

    // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 para 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetMailList", ReplyAction = "*")]
    GetMailListResponse GetMailList(GetMailListRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetMailList", ReplyAction = "*")]
    System.Threading.Tasks.Task<GetMailListResponse> GetMailListAsync(GetMailListRequest request);

    // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 para 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetOutMailList", ReplyAction = "*")]
    GetOutMailListResponse GetOutMailList(GetOutMailListRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetOutMailList", ReplyAction = "*")]
    System.Threading.Tasks.Task<GetOutMailListResponse> GetOutMailListAsync(GetOutMailListRequest request);

    // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 para 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetMailInfo", ReplyAction = "*")]
    GetMailInfoResponse GetMailInfo(GetMailInfoRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetMailInfo", ReplyAction = "*")]
    System.Threading.Tasks.Task<GetMailInfoResponse> GetMailInfoAsync(GetMailInfoRequest request);

    // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 para 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetAttInfo", ReplyAction = "*")]
    GetAttInfoResponse GetAttInfo(GetAttInfoRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/GetAttInfo", ReplyAction = "*")]
    System.Threading.Tasks.Task<GetAttInfoResponse> GetAttInfoAsync(GetAttInfoRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SendExRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendEx", Namespace = "http://tempuri.org/", Order = 0)]
    public SendExRequestBody Body;

    public SendExRequest()
    {
    }

    public SendExRequest(SendExRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SendExRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public string title;

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
    public string content;

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
    public string to;

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
    public tempuri.org.ArrayOfString AttachmentFilePaths;

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
    public tempuri.org.ArrayOfString cc;

    public SendExRequestBody()
    {
    }

    public SendExRequestBody(string title, string content, string to, tempuri.org.ArrayOfString AttachmentFilePaths, tempuri.org.ArrayOfString cc)
    {
        this.title = title;
        this.content = content;
        this.to = to;
        this.AttachmentFilePaths = AttachmentFilePaths;
        this.cc = cc;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SendExResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendExResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public SendExResponseBody Body;

    public SendExResponse()
    {
    }

    public SendExResponse(SendExResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SendExResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
    public int SendExResult;

    public SendExResponseBody()
    {
    }

    public SendExResponseBody(int SendExResult)
    {
        this.SendExResult = SendExResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SendRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "Send", Namespace = "http://tempuri.org/", Order = 0)]
    public SendRequestBody Body;

    public SendRequest()
    {
    }

    public SendRequest(SendRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SendRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public string title;

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
    public string content;

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
    public string to;

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
    public tempuri.org.ArrayOfString AttachmentFilePaths;

    public SendRequestBody()
    {
    }

    public SendRequestBody(string title, string content, string to, tempuri.org.ArrayOfString AttachmentFilePaths)
    {
        this.title = title;
        this.content = content;
        this.to = to;
        this.AttachmentFilePaths = AttachmentFilePaths;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SendResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public SendResponseBody Body;

    public SendResponse()
    {
    }

    public SendResponse(SendResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SendResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
    public int SendResult;

    public SendResponseBody()
    {
    }

    public SendResponseBody(int SendResult)
    {
        this.SendResult = SendResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SendToOfficeIMRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendToOfficeIM", Namespace = "http://tempuri.org/", Order = 0)]
    public SendToOfficeIMRequestBody Body;

    public SendToOfficeIMRequest()
    {
    }

    public SendToOfficeIMRequest(SendToOfficeIMRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SendToOfficeIMRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.OfficeIMMessageBody messageBody;

    public SendToOfficeIMRequestBody()
    {
    }

    public SendToOfficeIMRequestBody(tempuri.org.OfficeIMMessageBody messageBody)
    {
        this.messageBody = messageBody;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SendToOfficeIMResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendToOfficeIMResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public SendToOfficeIMResponseBody Body;

    public SendToOfficeIMResponse()
    {
    }

    public SendToOfficeIMResponse(SendToOfficeIMResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class SendToOfficeIMResponseBody
{

    public SendToOfficeIMResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SendToOfficeIMMulAttRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendToOfficeIMMulAtt", Namespace = "http://tempuri.org/", Order = 0)]
    public SendToOfficeIMMulAttRequestBody Body;

    public SendToOfficeIMMulAttRequest()
    {
    }

    public SendToOfficeIMMulAttRequest(SendToOfficeIMMulAttRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class SendToOfficeIMMulAttRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.OfficeIMMessageMuiltAttbBody messageBody;

    public SendToOfficeIMMulAttRequestBody()
    {
    }

    public SendToOfficeIMMulAttRequestBody(tempuri.org.OfficeIMMessageMuiltAttbBody messageBody)
    {
        this.messageBody = messageBody;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SendToOfficeIMMulAttResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SendToOfficeIMMulAttResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public SendToOfficeIMMulAttResponseBody Body;

    public SendToOfficeIMMulAttResponse()
    {
    }

    public SendToOfficeIMMulAttResponse(SendToOfficeIMMulAttResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class SendToOfficeIMMulAttResponseBody
{

    public SendToOfficeIMMulAttResponseBody()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetMailListRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetMailList", Namespace = "http://tempuri.org/", Order = 0)]
    public GetMailListRequestBody Body;

    public GetMailListRequest()
    {
    }

    public GetMailListRequest(GetMailListRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetMailListRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.GetMailPara para;

    public GetMailListRequestBody()
    {
    }

    public GetMailListRequestBody(tempuri.org.GetMailPara para)
    {
        this.para = para;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetMailListResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetMailListResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public GetMailListResponseBody Body;

    public GetMailListResponse()
    {
    }

    public GetMailListResponse(GetMailListResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetMailListResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.NewShowapi_res_body_listOfNewReceiveMailBodyEntity GetMailListResult;

    public GetMailListResponseBody()
    {
    }

    public GetMailListResponseBody(tempuri.org.NewShowapi_res_body_listOfNewReceiveMailBodyEntity GetMailListResult)
    {
        this.GetMailListResult = GetMailListResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetOutMailListRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetOutMailList", Namespace = "http://tempuri.org/", Order = 0)]
    public GetOutMailListRequestBody Body;

    public GetOutMailListRequest()
    {
    }

    public GetOutMailListRequest(GetOutMailListRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetOutMailListRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.GetMailPara para;

    public GetOutMailListRequestBody()
    {
    }

    public GetOutMailListRequestBody(tempuri.org.GetMailPara para)
    {
        this.para = para;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetOutMailListResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetOutMailListResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public GetOutMailListResponseBody Body;

    public GetOutMailListResponse()
    {
    }

    public GetOutMailListResponse(GetOutMailListResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetOutMailListResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.NewShowapi_res_body_listOfNewReceiveMailBodyEntity GetOutMailListResult;

    public GetOutMailListResponseBody()
    {
    }

    public GetOutMailListResponseBody(tempuri.org.NewShowapi_res_body_listOfNewReceiveMailBodyEntity GetOutMailListResult)
    {
        this.GetOutMailListResult = GetOutMailListResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetMailInfoRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetMailInfo", Namespace = "http://tempuri.org/", Order = 0)]
    public GetMailInfoRequestBody Body;

    public GetMailInfoRequest()
    {
    }

    public GetMailInfoRequest(GetMailInfoRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetMailInfoRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.GetMailInfoPara para;

    public GetMailInfoRequestBody()
    {
    }

    public GetMailInfoRequestBody(tempuri.org.GetMailInfoPara para)
    {
        this.para = para;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetMailInfoResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetMailInfoResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public GetMailInfoResponseBody Body;

    public GetMailInfoResponse()
    {
    }

    public GetMailInfoResponse(GetMailInfoResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetMailInfoResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.NewReceiveMailBodyEntity GetMailInfoResult;

    public GetMailInfoResponseBody()
    {
    }

    public GetMailInfoResponseBody(tempuri.org.NewReceiveMailBodyEntity GetMailInfoResult)
    {
        this.GetMailInfoResult = GetMailInfoResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetAttInfoRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetAttInfo", Namespace = "http://tempuri.org/", Order = 0)]
    public GetAttInfoRequestBody Body;

    public GetAttInfoRequest()
    {
    }

    public GetAttInfoRequest(GetAttInfoRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetAttInfoRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.GetMailInfoPara para;

    public GetAttInfoRequestBody()
    {
    }

    public GetAttInfoRequestBody(tempuri.org.GetMailInfoPara para)
    {
        this.para = para;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class GetAttInfoResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetAttInfoResponse", Namespace = "http://tempuri.org/", Order = 0)]
    public GetAttInfoResponseBody Body;

    public GetAttInfoResponse()
    {
    }

    public GetAttInfoResponse(GetAttInfoResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
public partial class GetAttInfoResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tempuri.org.AttachmentBean GetAttInfoResult;

    public GetAttInfoResponseBody()
    {
    }

    public GetAttInfoResponseBody(tempuri.org.AttachmentBean GetAttInfoResult)
    {
        this.GetAttInfoResult = GetAttInfoResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SendEmailSoapChannel : SendEmailSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SendEmailSoapClient : System.ServiceModel.ClientBase<SendEmailSoap>, SendEmailSoap
{

    public SendEmailSoapClient()
    {
    }

    public SendEmailSoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public SendEmailSoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public SendEmailSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public SendEmailSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SendExResponse SendEmailSoap.SendEx(SendExRequest request)
    {
        return base.Channel.SendEx(request);
    }

    public int SendEx(string title, string content, string to, tempuri.org.ArrayOfString AttachmentFilePaths, tempuri.org.ArrayOfString cc)
    {
        SendExRequest inValue = new SendExRequest();
        inValue.Body = new SendExRequestBody();
        inValue.Body.title = title;
        inValue.Body.content = content;
        inValue.Body.to = to;
        inValue.Body.AttachmentFilePaths = AttachmentFilePaths;
        inValue.Body.cc = cc;
        SendExResponse retVal = ((SendEmailSoap)(this)).SendEx(inValue);
        return retVal.Body.SendExResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SendExResponse> SendEmailSoap.SendExAsync(SendExRequest request)
    {
        return base.Channel.SendExAsync(request);
    }

    public System.Threading.Tasks.Task<SendExResponse> SendExAsync(string title, string content, string to, tempuri.org.ArrayOfString AttachmentFilePaths, tempuri.org.ArrayOfString cc)
    {
        SendExRequest inValue = new SendExRequest();
        inValue.Body = new SendExRequestBody();
        inValue.Body.title = title;
        inValue.Body.content = content;
        inValue.Body.to = to;
        inValue.Body.AttachmentFilePaths = AttachmentFilePaths;
        inValue.Body.cc = cc;
        return ((SendEmailSoap)(this)).SendExAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SendResponse SendEmailSoap.Send(SendRequest request)
    {
        return base.Channel.Send(request);
    }

    public int Send(string title, string content, string to, tempuri.org.ArrayOfString AttachmentFilePaths)
    {
        SendRequest inValue = new SendRequest();
        inValue.Body = new SendRequestBody();
        inValue.Body.title = title;
        inValue.Body.content = content;
        inValue.Body.to = to;
        inValue.Body.AttachmentFilePaths = AttachmentFilePaths;
        SendResponse retVal = ((SendEmailSoap)(this)).Send(inValue);
        return retVal.Body.SendResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SendResponse> SendEmailSoap.SendAsync(SendRequest request)
    {
        return base.Channel.SendAsync(request);
    }

    public System.Threading.Tasks.Task<SendResponse> SendAsync(string title, string content, string to, tempuri.org.ArrayOfString AttachmentFilePaths)
    {
        SendRequest inValue = new SendRequest();
        inValue.Body = new SendRequestBody();
        inValue.Body.title = title;
        inValue.Body.content = content;
        inValue.Body.to = to;
        inValue.Body.AttachmentFilePaths = AttachmentFilePaths;
        return ((SendEmailSoap)(this)).SendAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SendToOfficeIMResponse SendEmailSoap.SendToOfficeIM(SendToOfficeIMRequest request)
    {
        return base.Channel.SendToOfficeIM(request);
    }

    public void SendToOfficeIM(tempuri.org.OfficeIMMessageBody messageBody)
    {
        SendToOfficeIMRequest inValue = new SendToOfficeIMRequest();
        inValue.Body = new SendToOfficeIMRequestBody();
        inValue.Body.messageBody = messageBody;
        SendToOfficeIMResponse retVal = ((SendEmailSoap)(this)).SendToOfficeIM(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SendToOfficeIMResponse> SendEmailSoap.SendToOfficeIMAsync(SendToOfficeIMRequest request)
    {
        return base.Channel.SendToOfficeIMAsync(request);
    }

    public System.Threading.Tasks.Task<SendToOfficeIMResponse> SendToOfficeIMAsync(tempuri.org.OfficeIMMessageBody messageBody)
    {
        SendToOfficeIMRequest inValue = new SendToOfficeIMRequest();
        inValue.Body = new SendToOfficeIMRequestBody();
        inValue.Body.messageBody = messageBody;
        return ((SendEmailSoap)(this)).SendToOfficeIMAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SendToOfficeIMMulAttResponse SendEmailSoap.SendToOfficeIMMulAtt(SendToOfficeIMMulAttRequest request)
    {
        return base.Channel.SendToOfficeIMMulAtt(request);
    }

    public void SendToOfficeIMMulAtt(tempuri.org.OfficeIMMessageMuiltAttbBody messageBody)
    {
        SendToOfficeIMMulAttRequest inValue = new SendToOfficeIMMulAttRequest();
        inValue.Body = new SendToOfficeIMMulAttRequestBody();
        inValue.Body.messageBody = messageBody;
        SendToOfficeIMMulAttResponse retVal = ((SendEmailSoap)(this)).SendToOfficeIMMulAtt(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SendToOfficeIMMulAttResponse> SendEmailSoap.SendToOfficeIMMulAttAsync(SendToOfficeIMMulAttRequest request)
    {
        return base.Channel.SendToOfficeIMMulAttAsync(request);
    }

    public System.Threading.Tasks.Task<SendToOfficeIMMulAttResponse> SendToOfficeIMMulAttAsync(tempuri.org.OfficeIMMessageMuiltAttbBody messageBody)
    {
        SendToOfficeIMMulAttRequest inValue = new SendToOfficeIMMulAttRequest();
        inValue.Body = new SendToOfficeIMMulAttRequestBody();
        inValue.Body.messageBody = messageBody;
        return ((SendEmailSoap)(this)).SendToOfficeIMMulAttAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetMailListResponse SendEmailSoap.GetMailList(GetMailListRequest request)
    {
        return base.Channel.GetMailList(request);
    }

    public tempuri.org.NewShowapi_res_body_listOfNewReceiveMailBodyEntity GetMailList(tempuri.org.GetMailPara para)
    {
        GetMailListRequest inValue = new GetMailListRequest();
        inValue.Body = new GetMailListRequestBody();
        inValue.Body.para = para;
        GetMailListResponse retVal = ((SendEmailSoap)(this)).GetMailList(inValue);
        return retVal.Body.GetMailListResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetMailListResponse> SendEmailSoap.GetMailListAsync(GetMailListRequest request)
    {
        return base.Channel.GetMailListAsync(request);
    }

    public System.Threading.Tasks.Task<GetMailListResponse> GetMailListAsync(tempuri.org.GetMailPara para)
    {
        GetMailListRequest inValue = new GetMailListRequest();
        inValue.Body = new GetMailListRequestBody();
        inValue.Body.para = para;
        return ((SendEmailSoap)(this)).GetMailListAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetOutMailListResponse SendEmailSoap.GetOutMailList(GetOutMailListRequest request)
    {
        return base.Channel.GetOutMailList(request);
    }

    public tempuri.org.NewShowapi_res_body_listOfNewReceiveMailBodyEntity GetOutMailList(tempuri.org.GetMailPara para)
    {
        GetOutMailListRequest inValue = new GetOutMailListRequest();
        inValue.Body = new GetOutMailListRequestBody();
        inValue.Body.para = para;
        GetOutMailListResponse retVal = ((SendEmailSoap)(this)).GetOutMailList(inValue);
        return retVal.Body.GetOutMailListResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetOutMailListResponse> SendEmailSoap.GetOutMailListAsync(GetOutMailListRequest request)
    {
        return base.Channel.GetOutMailListAsync(request);
    }

    public System.Threading.Tasks.Task<GetOutMailListResponse> GetOutMailListAsync(tempuri.org.GetMailPara para)
    {
        GetOutMailListRequest inValue = new GetOutMailListRequest();
        inValue.Body = new GetOutMailListRequestBody();
        inValue.Body.para = para;
        return ((SendEmailSoap)(this)).GetOutMailListAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetMailInfoResponse SendEmailSoap.GetMailInfo(GetMailInfoRequest request)
    {
        return base.Channel.GetMailInfo(request);
    }

    public tempuri.org.NewReceiveMailBodyEntity GetMailInfo(tempuri.org.GetMailInfoPara para)
    {
        GetMailInfoRequest inValue = new GetMailInfoRequest();
        inValue.Body = new GetMailInfoRequestBody();
        inValue.Body.para = para;
        GetMailInfoResponse retVal = ((SendEmailSoap)(this)).GetMailInfo(inValue);
        return retVal.Body.GetMailInfoResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetMailInfoResponse> SendEmailSoap.GetMailInfoAsync(GetMailInfoRequest request)
    {
        return base.Channel.GetMailInfoAsync(request);
    }

    public System.Threading.Tasks.Task<GetMailInfoResponse> GetMailInfoAsync(tempuri.org.GetMailInfoPara para)
    {
        GetMailInfoRequest inValue = new GetMailInfoRequest();
        inValue.Body = new GetMailInfoRequestBody();
        inValue.Body.para = para;
        return ((SendEmailSoap)(this)).GetMailInfoAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetAttInfoResponse SendEmailSoap.GetAttInfo(GetAttInfoRequest request)
    {
        return base.Channel.GetAttInfo(request);
    }

    public tempuri.org.AttachmentBean GetAttInfo(tempuri.org.GetMailInfoPara para)
    {
        GetAttInfoRequest inValue = new GetAttInfoRequest();
        inValue.Body = new GetAttInfoRequestBody();
        inValue.Body.para = para;
        GetAttInfoResponse retVal = ((SendEmailSoap)(this)).GetAttInfo(inValue);
        return retVal.Body.GetAttInfoResult;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetAttInfoResponse> SendEmailSoap.GetAttInfoAsync(GetAttInfoRequest request)
    {
        return base.Channel.GetAttInfoAsync(request);
    }

    public System.Threading.Tasks.Task<GetAttInfoResponse> GetAttInfoAsync(tempuri.org.GetMailInfoPara para)
    {
        GetAttInfoRequest inValue = new GetAttInfoRequest();
        inValue.Body = new GetAttInfoRequestBody();
        inValue.Body.para = para;
        return ((SendEmailSoap)(this)).GetAttInfoAsync(inValue);
    }
}
